name: Build and deploy Node.js app to Azure Web App - BoostWork

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create deployment package
        run: |
          cd Backend
          zip -r ../deploy.zip . -x "node_modules/*" ".env" ".git/*"

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_BD1A2E0E8BEB47FEA94EB61867983330 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_A6984B9634D84A48ACE6F5728AC610BB }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_A174D98861964751BD0689C84924E210 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'BoostWork'
          package: deploy.zip
